name: Testing Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Monika NPM version to create docker image'
        required: true
        type: string

jobs:
  testing:
    name: Testing Release
    if: github.repository == 'nicnocquee/monika-lukman'
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⤴️ Switch Version based on inputs
        id: version
        run: |
          git config --local user.email "monika@hyperjump.tech"
          git config --local user.name "Monika Bot"
          git fetch --all --tags
          git checkout -b "${{ inputs.version }}"
          echo ::set-output name=VERSION::${{ inputs.version }}
          if [ -z "$(git status --porcelain)" ]; then
              echo "✨"
          fi
          npm version --no-git-tag-version

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            nicnocquee/monika-test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HYPERJUMP_DOCKER_USERNAME }}
          password: ${{ secrets.HYPERJUMP_DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nicnocquee/monika-test:${{ inputs.version }}
